const wp_list = [
    // Access to Justice in the Age of AI: Evidence from U.S. Federal Courts
    {
        title : "Access to Justice in the Age of AI: Evidence from U.S. Federal Courts",
        year : 2026,
        authors : [
            {authorName : "Anand Shah", authorWebsiteLink : "https://avshah1.github.io", authorWebsiteLinkNewTabOpt : true},
            {authorName : "Joshua Levy", authorWebsiteLink : "/", authorWebsiteLinkNewTabOpt : false},
        ],
        abstract : "This paper studies how generative AI has reshaped entry into the federal civil court system. Drawing on administrative records covering more than 4.5 million non-prisoner federal civil court cases from FY2005-FY2026 and 46 million PACER docket entries matched to those cases, we document three sets of findings. First, the number of <em>pro se</em> cases&mdash;or self-represented cases&mdash;is increasing dramatically, rising from a long-term steady-state average of 11% to 16.8% in FY2025. This increase is concentrated in case types characterized by formulaic document production and absent from more complex, attorney-intensive categories. Second, we argue these cases are placing larger burden on federal district courts. <em>Pro se</em> cases are not terminating faster, and this combined with the increased case numbers suggests more cases for judges to process. Moreover, intra-case activity is up, with the total volume of docket entries per court generated by <em>pro se</em> cases in their first 180 days up 158% from pre-AI means to 2025. Third, we directly validate that AI use is increasing in federal courts. Using a random sample of 1,600 complaints drawn from an 8-year period (2019-2026), we find that a large and growing share of complaints are flagging positive for AI-generated text, from essentially zero in the pre-AI period to more than 18% in 2026.",
   
        status : "",
        pubvenue : "SSRN",
        downloadPath : "/",
        downloadTabOpt : true,
        otherButtons : [
            // {buttonText : "buttonText1", buttonLink: "/", buttonNewTabOpt : false}
        ],
        media : [
            // {mediaPubName : "PoliticoEU", mediaLink : "https://www.politico.eu/newsletter/politico-eu-influence/hi-youre-through-to-the-conflicts-of-interest-hotline/#:~:text=Reinier%20van%20Zutphen.-,TRUSTING%20SOURCES%3A,-Conflicts%20of%20interest", buttonNewTabOpt : true}
        ]
    },
    // The Conflict-of-Interest Discount in the Marketplace of Ideas
    {
        title : "The Conflict-of-Interest Discount in the Marketplace of Ideas",
        year : 2025,
        authors : [
            {authorName : "John M. Barrios", authorWebsiteLink : "https://www.johnmbarrios.com/", authorWebsiteLinkNewTabOpt : true},
            {authorName : "Filippo Lancieri", authorWebsiteLink : "https://www.law.georgetown.edu/faculty/filippo-lancieri/", authorWebsiteLinkNewTabOpt : true},
            {authorName : "Joshua Levy", authorWebsiteLink : "/", authorWebsiteLinkNewTabOpt : false},
            {authorName : "Shashank Singh", authorWebsiteLink : "https://shashanksinghnain.github.io/", authorWebsiteLinkNewTabOpt : true},
            {authorName : "Tommaso M. Valletti", authorWebsiteLink : "https://profiles.imperial.ac.uk/t.valletti", authorWebsiteLinkNewTabOpt : true},
            {authorName : "Luigi Zingales", authorWebsiteLink : "https://faculty.chicagobooth.edu/luigi-zingales", authorWebsiteLinkNewTabOpt : true},

        ],
        abstract : "We conduct a survey of economists and a representative sample of Americans to infer the reduction in the perceived value of a paper when its authors have conflicts of interest (CoI), i.e., they have financial, professional, or ideological stakes in the outcome of the results. On average, a CoI decreases trust in the conclusions of an economics paper by 30%. This reduction in trust reflects a combination of the frequency of conflicted papers and the bias of papers when they are conflicted. To isolate the second term, we introduce a key construct: the CoI Discount, which measures the reduction in the value of a conflicted paper relative to a non-conflicted one. We show that, on average, conflicted papers are worth less than half of non-conflicted ones, though this effect varies significantly depending on the nature of the conflict. The discount is more pronounced when the conflict involves the interest of a private rather than a public entity. Restricted data access also leads to a substantial discount. We validate our survey based estimates by comparing them to actual biases observed in conflicted papers within the economics and medical literature.",
        status : "",
        pubvenue : "NBER",
        downloadPath : "/research_pdfs/COI-04-25-NBER.pdf",
        downloadTabOpt : true,
        otherButtons: [
            {buttonText : "NBER", buttonLink: "https://www.nber.org/papers/w33645", buttonNewTabOpt : true},
            {buttonText : "SSRN", buttonLink: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4979205", buttonNewTabOpt : true}

        ],
        media : [
            {mediaPubName : "Stigler Center (video)", mediaLink : "https://www.youtube.com/watch?v=EU7EnP9xLrw", buttonNewTabOpt : true},
            {mediaPubName : "PoliticoEU", mediaLink : "https://www.politico.eu/newsletter/politico-eu-influence/hi-youre-through-to-the-conflicts-of-interest-hotline/#:~:text=Reinier%20van%20Zutphen.-,TRUSTING%20SOURCES%3A,-Conflicts%20of%20interest", buttonNewTabOpt : true},
            {mediaPubName : "Frankfurter Allgemeine", mediaLink : "https://www.faz.net/aktuell/wissen/forschung-politik/studie-ueber-interessenkonflikte-in-der-wissenschaft-110075764.html", buttonNewTabOpt : true},
        ]
    }
]


export default wp_list;
